redirects:
  license: ./README.md
  1-axon-framework/introduction: ./README.md
  1-axon-framework/getting-started: ./introduction/quick-start.md
  1.1-concepts/architecture-overview: ./introduction/architecture-overview/architecture-overview.md
  1.1-concepts/messaging-concepts: ./axon-framework/messaging-concepts/README.md
  1.2-domain-logic/command-model: ./axon-framework/axon-framework-commands/README.md
  1.2-domain-logic/event-handling: ./axon-framework/events/README.md
  1.2-domain-logic/query-handling: ./axon-framework/queries/README.md
  1.2-domain-logic/sagas: ./axon-framework/sagas/README.md
  1.2-domain-logic/deadlines: ./axon-framework/deadlines/README.md
  1.2-domain-logic/testing: ./axon-framework/testing/README.md
  1.3-infrastructure-components/command-dispatching: ./axon-framework/axon-framework-commands/command-dispatchers.md
  1.3-infrastructure-components/event-processing: ./axon-framework/events/README.md
  1.3-infrastructure-components/query-processing: ./axon-framework/queries/query-processing.md
  1.3-infrastructure-components/repository-and-event-store: ./axon-framework/events/event-bus-and-event-store.md
  1.3-infrastructure-components/spring-boot-autoconfiguration: ./getting-started/quick-start.md
  1.4-advanced-tuning/advanced-customizations: ./axon-framework/tuning/README.md
  1.4-advanced-tuning/performance-tuning: ./axon-framework/tuning/README.md
  1.4-advanced-tuning/metrics-and-monitoring: ./axon-framework/monitoring/README.md
  2-axon-server/about: ./axon-server/introduction.md
  2-axon-server/getting-started: ./getting-started/quick-start.md
  2-axon-server/architecture: ./introduction/axon-server.md
  2.1-setup/starting-axonserver: ./axon-server/installation/README.md
  2.1-setup/configuration: ./axon-server/administration/README.md
  2.1-setup/clustering: ./axon-server/administration/clustering.md
  2.1-setup/multi-context: ./axon-server/administration/multi-context.md
  2.2-operations/backups: ./axon-server/administration/backups.md
  2.2-operations/monitoring: ./axon-server/administration/monitoring/README.md


